services:
  bandcamp-dl:
    image: ghcr.io/2tap2b/bandcamp-dl-webui:latest
    ports:
      - "5000:5000"
    user: "1000:1000"
    volumes:
      - /mnt/nfs_share/punkify:/downloads
    environment:
      - DOWNLOAD_DIR=/downloads
    restart: unless-stopped
