name: Build and Push

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to registry
        run: |
          echo "${{ secrets.REGISTRY_TOKEN }}" | \
          docker login git.steltner.cloud -u ${{ vars.REGISTRY_USER }} --password-stdin

      - name: Build and push
        run: |
          IMAGE=git.steltner.cloud/${{ gitea.repository }}:latest
          docker build -t $IMAGE .
          docker push $IMAGE